name: git_hooks_example
version: 0.0.1
homepage: https://github.com/xuzhongpeng/git_hooks
author: xuzhongpeng <1452754335@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  git_hooks:
    path: ../
